### ISSUE TITLE
请问如何在自己的图片上推理呢

### ISSUE THREAD

**Issue by Tavish77** [shannanyinxiang/PageNet#3]

**Comment by shannanyinxiang** [comment]
您好，可以将`data/`中的数据预处理和`engine/val.py`中的模型前向及解码部分结合起来，实现对输入图片的推理。

**Comment by Tavish77** [comment]
![Uploading 微信图片_20230613094432.png…]()

输入数据格式不是常规的H*W*C吗

**Comment by Tavish77** [comment]
`RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 1, 3, 3], but got 3-dimensional input of size [245, 569, 3] instead`

输入格式似乎不是常规的H*W*C？

**Comment by shannanyinxiang** [comment]
输入格式是NCHW（N是batch size）。
对于CASIA-HWDB训练的模型，采用的是灰度图，通道数为1，其余为3.

**Comment by Tavish77** [comment]
谢谢
