### ISSUE TITLE
你好，请问下这个数据（SCUT-HCCDoc_Dataset_Release）的解压密码是啥

### ISSUE THREAD

**Issue by fxwfzsxyq** [shannanyinxiang/PageNet#6]

**Comment by shannanyinxiang** [comment]
您好，需要按照网站（https://github.com/HCIILAB/SCUT-HCCDoc_Dataset_Release）的要求向数据集所有者申请密码。

**Comment by fxwfzsxyq** [comment]
好的 谢谢
&nbsp;


snake
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月23日(星期二) 下午5:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shannanyinxiang/PageNet] 你好，请问下这个数据（SCUT-HCCDoc_Dataset_Release）的解压密码是啥 (Issue #6)





 
您好，需要按照网站（https://github.com/HCIILAB/SCUT-HCCDoc_Dataset_Release）的要求向数据集所有者申请密码。
